AllCops:
  Include:
    - './Rakefile'
    - 'instapaper.gemspec'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
  DisplayCopNames: true

Metrics/BlockNesting:
  Max: 2

Metrics/LineLength:
  AllowURI: true
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 10

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: true

Style/CollectionMethods:
  PreferredMethods:
    map:      'collect'
    reduce:   'inject'
    find:     'detect'
    find_all: 'select'

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: 'comma'

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: 'comma'
